name: 'my first container action'
description: 'a Cloud Guru'
author: 'Mike Grundy'
inputs:
  myInput:
    description: 'greeting to use'
    required: true
    default: 'Awesome Guru'
outputs:
  myOutputs:
    description: 'total memory'
runs:
  using: 'docker'
  image: 'Dockerfile'

  
